name: DevOps CI pipeline
on: [push]
jobs:
  build:
    runs -on: ubuntu-latest
  steps:
    -name: checkout code
     uses: actions/checkout@v2
    -name: build docker image
     run:  docker build -t ci-demo-app
